### ISSUE TITLE
URGENT!

### ISSUE THREAD

**Issue by mirhendi** [GrowingDegreeDay/Project1#7]
Hi,
I think made a mistake during using GIT and made some changes to other's code.
Would someone please restore that?
Sorry :(

**Comment by CsongorMatyas** [comment]
Is it ok now? can we push or pull?

**Comment by mirhendi** [comment]
I'm not sure whether I made any mistake or not! and I don't know what
happened. I have my own code and nothing is important about that. would you
please correct any mistake that I did?
Thanks


On Thu, Jun 9, 2016 at 4:15 PM, Csongor Matyas <notifications@github.com>
wrote:

> Is it ok now? can we push or pull?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/GrowingDegreeDay/Project1/issues/7#issuecomment-224989320>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AH3TpBXl149kTh2j_vC-J-JpJziMGsFpks5qKF8vgaJpZM4IyOCn>
> .
>



-- 
S. Sadra Mirhendi

**Comment by CsongorMatyas** [comment]
I'm not sure what you did, but it seems ok for me after pull and push.

**Comment by mirhendi** [comment]
That's fine Thank you

On Thu, Jun 9, 2016 at 4:30 PM, Csongor Matyas <notifications@github.com>
wrote:

> I'm not sure what you did, but it seems ok for me after pull and push.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/GrowingDegreeDay/Project1/issues/7#issuecomment-224993684>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AH3TpCIPtYM7tYUmZTloZQ8kFRiL-TSSks5qKGLegaJpZM4IyOCn>
> .
>



-- 
S. Sadra Mirhendi
