### ISSUE TITLE
Meeting

### ISSUE THREAD

**Issue by scu677** [GrowingDegreeDay/Project1#8]
Is there any chance for us to meet tomorrow 10am -1pm just to know what have done so far and what is left to do?
 Your ideas please?

**Comment by CsongorMatyas** [comment]
I'm free tomorrow at that time, and the meeting is a good idea.

**Comment by CsongorMatyas** [comment]
So please let me know if we are meeting tomorrow at 11 or I can stay home until 12 :)

**Comment by jdowzell** [comment]
I am good to meet at 10 if others are?

**Comment by CsongorMatyas** [comment]
Just woke up, I was up almost all night. Please let me know when we meet. It can be 10 but than I have to leave now. I think we are good in terms of the code, better than I thought, but we still have to discuss stuff and put things together. We can do it online, but meeting would be better.

**Comment by jdowzell** [comment]
Holy cow dude, if you've been up all night, get yourself some rest :P I can meet any time after 1pm if that works better for people?

**Comment by scu677** [comment]
I was about to leave my house now, but seem I reach there and meet no
one...hahaha. I will still be in school but will leave around 1pm

**Comment by CsongorMatyas** [comment]
Ok than lets meet 10:30 at the lab (Classroom). Leave your phone number on the group email if you will be late, or call me or Jake and we will guide you to where we actually sat down.

**Comment by jdowzell** [comment]
Running a tad late but on my way

**Comment by scu677** [comment]
Guys I am in the library 3rd floor. where are you?

**Comment by CsongorMatyas** [comment]
We just met with Jake and Sandra will drop in at 1:30. I will go to the library now, please don't move.
